services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: demo_db
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: demo_password
    ports:
      - "3307:3306"  # Ändere den Host-Port auf 3307
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: